"""
Emit the v1.2 adjudication workflow script with the locked prompt template
and the 230 player profiles inlined as a const. The emitted .js is what
the Workflow tool reads via scriptPath.

Locked prompt template = AMENDMENT_v1.2 section 2.3 — embedded verbatim
inside a JS template literal. Locked schema = AMENDMENT_v1.2 section 2.4.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PIPE = Path(r"D:/NBA Projections/RMD_SRC_PIPELINE")
PROFILES = PIPE / "results" / "adjudication_profiles_v12.json"
OUT = PIPE / "src" / "adjudicate_v12_run.js"


PROMPT_TEMPLATE = r"""You are adjudicating a single NBA player's best-fit position bucket for a methodology paper substrate. The bucket choices are:
  Center, Forward, Guard, or no_fit.

You will NOT be told what the methodology paper concludes about position. Your only job is to pick the bucket that best reflects this player's on-court archetype across the 2019-20 through 2025-26 NBA seasons, using ONLY the data provided in this prompt.

Decision criteria (in priority order):
  1. Career on-court archetype during the 2019-26 window: where does this player primarily defend, and where does the offense use them?
  2. Height: > 6'10" leans Center; 6'7" - 6'10" can be either Forward or Center depending on role; < 6'7" leans Guard or stretch-3 Forward.
  3. Yahoo primary_position as a tie-breaker between two close options.
  4. Career counting-stat profile: high REB / BLK with low AST -> Center archetype; balanced REB / AST with moderate BLK -> Forward archetype; high AST with low REB -> Guard archetype.
  5. Era and rotation context: a player who debuted before 2010 may have played a different role earlier than what defines them in the 2019-26 window. The window is what matters.

The `no_fit` disposition: choose `no_fit` ONLY if the player's archetype is genuinely positionless in the 2019-26 window (truly straddles 2+ buckets without a primary one). `no_fit` is a real disposition, not a fallback when uncertain. If you can pick a primary bucket with even modest confidence, do so.

Return your verdict via the structured output tool.

The player to adjudicate:
  name: __NAME__
  metadata_position: __METAPOS__
  metadata_bucket_v1: __METAB__
  yahoo_eligible_positions: __YE__
  yahoo_primary_position: __YPRIM__
  height_inches: __HEIGHT__
  debut_year: __DEBUT__
  last_seen_season: __LASTSEEN__
  career_avg_REB_per36: __REB__
  career_avg_AST_per36: __AST__
  career_avg_BLK_per36: __BLK__
  career_avg_FG3M_per36: __FG3M__
"""


SCRIPT_HEADER = r"""// AUTO-GENERATED by RMD_SRC_PIPELINE/src/write_adjudication_workflow.py
// Locked under v1.2 amendment (SHA 1bfdb4c). Do NOT edit by hand; the
// adjudication agent fleet runs ONCE per amendment §6.

export const meta = {
  name: 'nba-position-adjudication-v12',
  description: 'Adjudicate 230 multi-eligible NBA players into Center/Forward/Guard/Positionless. Locked at v1.2 SHA 1bfdb4c.',
  phases: [
    { title: 'Adjudicate', detail: 'One Sonnet agent per player, 230 total, structured verdict' },
  ],
}

const VERDICT_SCHEMA = {
  type: "object",
  properties: {
    assignment:    { type: "string", enum: ["Center", "Forward", "Guard", "no_fit"] },
    confidence:    { type: "string", enum: ["high", "medium", "low"] },
    rationale:     { type: "string", maxLength: 600 },
    no_fit_reason: { type: "string", maxLength: 400 },
  },
  required: ["assignment", "confidence", "rationale"]
}

const PROMPT_TEMPLATE = """ + "`" + r"""__PROMPT_TEMPLATE_PLACEHOLDER__""" + "`" + r""";

function buildPrompt(p) {
  return PROMPT_TEMPLATE
    .replace('__NAME__',     p.name)
    .replace('__METAPOS__',  p.metadata_position || 'unknown')
    .replace('__METAB__',    p.metadata_bucket_v1)
    .replace('__YE__',       p.yahoo_eligible_positions || 'none')
    .replace('__YPRIM__',    p.yahoo_primary_position || 'none')
    .replace('__HEIGHT__',   p.height_inches != null ? String(p.height_inches) : 'unknown')
    .replace('__DEBUT__',    p.debut_year != null ? String(p.debut_year) : 'unknown')
    .replace('__LASTSEEN__', p.last_seen_season || 'unknown')
    .replace('__REB__',      p.career_avg_REB_per36 != null ? String(p.career_avg_REB_per36) : 'unknown')
    .replace('__AST__',      p.career_avg_AST_per36 != null ? String(p.career_avg_AST_per36) : 'unknown')
    .replace('__BLK__',      p.career_avg_BLK_per36 != null ? String(p.career_avg_BLK_per36) : 'unknown')
    .replace('__FG3M__',     p.career_avg_FG3M_per36 != null ? String(p.career_avg_FG3M_per36) : 'unknown')
}

const PROFILES = __PROFILES_PLACEHOLDER__;

phase('Adjudicate')
log(`v1.2 adjudication firing on ${PROFILES.length} player profiles (Sonnet, max-16 concurrent).`)

const results = await parallel(
  PROFILES.map((p) => () =>
    agent(buildPrompt(p), {
      schema: VERDICT_SCHEMA,
      label: `${p.metadata_bucket_v1[0]}:${p.name}`,
      model: 'sonnet',
    }).then((v) => ({
      nba_api_id:         p.nba_api_id,
      name:               p.name,
      metadata_bucket_v1: p.metadata_bucket_v1,
      adjudicated_bucket: v.assignment === 'no_fit' ? 'Positionless' : v.assignment,
      raw_assignment:     v.assignment,
      confidence:         v.confidence,
      rationale:          v.rationale,
      no_fit_reason:      v.no_fit_reason || '',
    }))
  )
)

const verdicts = results.filter(Boolean)
const n_failed = results.length - verdicts.length

const bucket_counts = {}
for (const v of verdicts) {
  bucket_counts[v.adjudicated_bucket] = (bucket_counts[v.adjudicated_bucket] || 0) + 1
}

log(`Adjudication complete. ${verdicts.length}/${results.length} succeeded; bucket counts: ${JSON.stringify(bucket_counts)}.`)

return {
  n_total:        results.length,
  n_success:      verdicts.length,
  n_failed:       n_failed,
  bucket_counts:  bucket_counts,
  verdicts:       verdicts,
}
"""


def main() -> int:
    profiles = json.loads(PROFILES.read_text(encoding="utf-8"))
    print(f"Loaded {len(profiles)} profiles.")

    # Inline profiles as a JSON literal (valid JS).
    profiles_js = json.dumps(profiles, ensure_ascii=True)
    # Inline locked prompt template (escape any backtick that might appear — none expected).
    pt = PROMPT_TEMPLATE.replace("`", "\\`")

    script = (SCRIPT_HEADER
               .replace("__PROMPT_TEMPLATE_PLACEHOLDER__", pt)
               .replace("__PROFILES_PLACEHOLDER__", profiles_js))

    OUT.write_text(script, encoding="utf-8")
    print(f"Wrote workflow script: {OUT}")
    print(f"  script size: {len(script):,} chars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
