# Auto-generated by apply_fetcher_schedule.ps1 - DO NOT EDIT BY HAND.
# Source: D:\NBA Projections\config\fetcher_schedule.yaml
# Task:   NBA-CtG-Players-Run
$ErrorActionPreference = 'Continue'
$root   = 'C:\NBA Cleaning the Glass'
$python = 'C:\Users\Nate\AppData\Local\Programs\Python\Python312\python.exe'
$logDir = Join-Path $root 'logs'
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
$stamp  = Get-Date -Format 'yyyyMMdd_HHmm'
$log    = Join-Path $logDir ('NBA-CtG-Players-Run' + '_' + $stamp + '.log')
Set-Location $root

$today     = (Get-Date).ToString('yyyy-MM-dd')
$yesterday = (Get-Date).AddDays(-1).ToString('yyyy-MM-dd')

$commands = @'
python -m fetchers.cleaning_the_glass players

'@ -split "`r?`n" | Where-Object { $_.Trim() -ne '' }

$failed = 0
foreach ($raw in $commands) {
  $cmd = $raw -replace '\{\{today\}\}', $today -replace '\{\{yesterday\}\}', $yesterday
  $cmd = $cmd -replace '^python\b', ('"' + $python + '"')
  Add-Content -Path $log -Value ('>> ' + $cmd)
  Invoke-Expression "$cmd 2>&1 | Tee-Object -Append -FilePath $log"
  if ($LASTEXITCODE -ne 0) { $failed++ }
}

# Append a status row to fetcher_status.parquet
& $python -c @'
import sys, datetime as dt, pandas as pd
from pathlib import Path
out = Path(r"D:/NBA Projections/data/parquet/fetcher_status.parquet")
row = {
  "task_name":    sys.argv[1],
  "last_run_utc": dt.datetime.now(dt.timezone.utc),
  "exit_code":    int(sys.argv[2]),
  "log_path":     sys.argv[3],
}
df_new = pd.DataFrame([row])
if out.exists():
    cur = pd.read_parquet(out)
    cur = cur[cur["task_name"] != row["task_name"]]
    df = pd.concat([cur, df_new], ignore_index=True)
else:
    df = df_new
out.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(out, index=False)
'@ 'NBA-CtG-Players-Run' $failed $log

exit $failed
