#requires -Version 5.1
<#
Apply the YAML-defined fetcher schedule to Windows Task Scheduler.

Reads:  D:\NBA Projections\config\fetcher_schedule.yaml
Writes: D:\NBA Projections\config\fetcher_runners\<TaskName>.ps1
Registers/updates Windows Scheduled Tasks under prefix "NBA-".

Usage:
  powershell -ExecutionPolicy Bypass -File "D:\NBA Projections\config\apply_fetcher_schedule.ps1"
  powershell -ExecutionPolicy Bypass -File "D:\NBA Projections\config\apply_fetcher_schedule.ps1" -Mode inseason
  powershell -ExecutionPolicy Bypass -File "D:\NBA Projections\config\apply_fetcher_schedule.ps1" -DryRun
  powershell -ExecutionPolicy Bypass -File "D:\NBA Projections\config\apply_fetcher_schedule.ps1" -PruneUnknown

YAML parsing is delegated to Python (PyYAML) which dumps JSON to stdout;
PowerShell ingests via ConvertFrom-Json. No PowerShell-side YAML dependencies.
#>
[CmdletBinding()]
param(
  [ValidateSet('offseason','inseason')]
  [string]$Mode = 'offseason',
  [switch]$DryRun,
  [switch]$PruneUnknown
)

$ErrorActionPreference = 'Stop'
$ConfigPath  = 'D:\NBA Projections\config\fetcher_schedule.yaml'
$RunnersDir  = 'D:\NBA Projections\config\fetcher_runners'
$Python      = 'C:\Users\Nate\AppData\Local\Programs\Python\Python312\python.exe'

function Read-YamlAsJson {
  param([string]$Path)
  $py = "import yaml,json,sys; print(json.dumps(yaml.safe_load(open(sys.argv[1], encoding='utf-8'))))"
  $json = & $Python -c $py $Path
  if ($LASTEXITCODE -ne 0) { throw "Failed to parse YAML: $Path" }
  return $json | ConvertFrom-Json
}

function Get-DowMap { @{ Mon='Monday'; Tue='Tuesday'; Wed='Wednesday'; Thu='Thursday'; Fri='Friday'; Sat='Saturday'; Sun='Sunday' } }

function New-Trigger {
  param($Schedule)
  $kind = "$($Schedule.kind)"
  switch ($kind) {
    'daily' {
      $start = (Get-Date).Date.Add([TimeSpan]::Parse($Schedule.at))
      if ($start -lt (Get-Date)) { $start = $start.AddDays(1) }
      return New-ScheduledTaskTrigger -Daily -At $start
    }
    'weekly' {
      $dow = (Get-DowMap)[$Schedule.day]
      if (-not $dow) { throw "Unknown day-of-week: $($Schedule.day)" }
      $start = (Get-Date).Date.Add([TimeSpan]::Parse($Schedule.at))
      return New-ScheduledTaskTrigger -Weekly -DaysOfWeek $dow -At $start
    }
    'annual' {
      $year = (Get-Date).Year
      $next = Get-Date -Year $year -Month $Schedule.month -Day $Schedule.day -Hour 0 -Minute 0 -Second 0
      $next = $next.Add([TimeSpan]::Parse($Schedule.at))
      if ($next -lt (Get-Date)) { $next = $next.AddYears(1) }
      return New-ScheduledTaskTrigger -Daily -DaysInterval 365 -At $next
    }
    'repeat' {
      $hours = [int]$Schedule.every_hours
      $now = Get-Date
      $next = $now.Date.AddHours([math]::Floor($now.Hour / $hours + 1) * $hours)
      $base = New-ScheduledTaskTrigger -Once -At $next
      $base.Repetition = (New-ScheduledTaskTrigger -Once -At $next `
        -RepetitionInterval (New-TimeSpan -Hours $hours) `
        -RepetitionDuration ([TimeSpan]::FromDays(365 * 10))).Repetition
      return $base
    }
    default { throw "Unknown schedule kind: $kind" }
  }
}

function Write-Wrapper {
  param([string]$TaskName, [string]$RepoPath, [string]$Command, [string]$WrapperPath)

  $body = @"
# Auto-generated by apply_fetcher_schedule.ps1 - DO NOT EDIT BY HAND.
# Source: D:\NBA Projections\config\fetcher_schedule.yaml
# Task:   $TaskName
`$ErrorActionPreference = 'Continue'
`$root   = '$RepoPath'
`$python = '$Python'
`$logDir = Join-Path `$root 'logs'
New-Item -ItemType Directory -Force -Path `$logDir | Out-Null
`$stamp  = Get-Date -Format 'yyyyMMdd_HHmm'
`$log    = Join-Path `$logDir ('$TaskName' + '_' + `$stamp + '.log')
Set-Location `$root

`$today     = (Get-Date).ToString('yyyy-MM-dd')
`$yesterday = (Get-Date).AddDays(-1).ToString('yyyy-MM-dd')

`$commands = @'
$Command
'@ -split "``r?``n" | Where-Object { `$_.Trim() -ne '' }

`$failed = 0
foreach (`$raw in `$commands) {
  `$cmd = `$raw -replace '\{\{today\}\}', `$today -replace '\{\{yesterday\}\}', `$yesterday
  `$cmd = `$cmd -replace '^python\b', ('"' + `$python + '"')
  Add-Content -Path `$log -Value ('>> ' + `$cmd)
  Invoke-Expression "`$cmd 2>&1 | Tee-Object -Append -FilePath `$log"
  if (`$LASTEXITCODE -ne 0) { `$failed++ }
}

# Append a status row to fetcher_status.parquet
& `$python -c @'
import sys, datetime as dt, pandas as pd
from pathlib import Path
out = Path(r"D:/NBA Projections/data/parquet/fetcher_status.parquet")
row = {
  "task_name":    sys.argv[1],
  "last_run_utc": dt.datetime.now(dt.timezone.utc),
  "exit_code":    int(sys.argv[2]),
  "log_path":     sys.argv[3],
}
df_new = pd.DataFrame([row])
if out.exists():
    cur = pd.read_parquet(out)
    cur = cur[cur["task_name"] != row["task_name"]]
    df = pd.concat([cur, df_new], ignore_index=True)
else:
    df = df_new
out.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(out, index=False)
'@ '$TaskName' `$failed `$log

exit `$failed
"@

  Set-Content -LiteralPath $WrapperPath -Value $body -Encoding utf8
}

# ---------- Main ----------
Write-Host "Loading schedule from $ConfigPath ..."
$cfg = Read-YamlAsJson -Path $ConfigPath
if (-not $cfg.tasks) { throw "No 'tasks' key in YAML" }

New-Item -ItemType Directory -Force -Path $RunnersDir | Out-Null

$registered = @()
$skipped = @()
foreach ($task in $cfg.tasks) {
  $name = $task.name
  $repo = $task.repo
  $sched = if ($task.schedule -and $task.schedule.$Mode) { $task.schedule.$Mode } else { $null }

  if ($task.managed_externally) {
    Write-Host "  [SKIP managed externally] $name"
    $skipped += $name
    continue
  }
  if (-not $sched) {
    Write-Host "  [SKIP no $Mode schedule] $name"
    $skipped += $name
    continue
  }

  $wrapper = Join-Path $RunnersDir ("$name.ps1")
  # Apply-time interpolation: {{mode}} resolves to the mode flag this apply
  # is registering for. Wrapper-time tokens ({{today}}, {{yesterday}}) are
  # interpolated by the wrapper at run time.
  $cmd = $task.command -replace '\{\{mode\}\}', $Mode
  Write-Wrapper -TaskName $name -RepoPath $repo -Command $cmd -WrapperPath $wrapper

  $action = New-ScheduledTaskAction -Execute 'powershell.exe' `
              -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$wrapper`""
  $trigger = New-Trigger -Schedule $sched
  $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries `
                -DontStopIfGoingOnBatteries -RunOnlyIfNetworkAvailable `
                -ExecutionTimeLimit (New-TimeSpan -Hours 4)
  $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

  $desc = "$($task.purpose)  [mode=$Mode  yaml-managed]"

  if ($DryRun) {
    Write-Host ("  [DRYRUN] {0,-32} kind={1,-7} -> {2}" -f $name, $sched.kind, $wrapper)
  } else {
    Register-ScheduledTask -TaskName $name -Action $action -Trigger $trigger `
      -Settings $settings -Principal $principal -Description $desc -Force | Out-Null
    $info = Get-ScheduledTask -TaskName $name | Get-ScheduledTaskInfo
    Write-Host ("  [OK]     {0,-32} kind={1,-7} next={2}" -f $name, $sched.kind, $info.NextRunTime)
  }
  $registered += $name
}

if ($PruneUnknown) {
  $existing = Get-ScheduledTask | Where-Object { $_.TaskName -like 'NBA-*' } | Select-Object -ExpandProperty TaskName
  foreach ($t in $existing) {
    if ($registered -notcontains $t -and $skipped -notcontains $t) {
      Write-Host "  [PRUNE] $t"
      if (-not $DryRun) { Unregister-ScheduledTask -TaskName $t -Confirm:$false }
    }
  }
}

Write-Host ""
Write-Host "Registered: $($registered.Count)   Skipped: $($skipped.Count)   Mode: $Mode"
